### ISSUE TITLE
MissingRegion: could not find region configuration

### ISSUE THREAD

**Issue by Chan-Ko** [aws/aws-secretsmanager-caching-go#5]
## Overview
I tried reading README and then implemented, but the following error occurs
`MissingRegion: could not find region configuration`

You will probably have to add a `Region` to the session information when doing `secretsmanager.New()`

This error has already occurred in the sample code generated by secretsmanager...

**Comment by Chan-Ko** [comment]
Sorry...
It worked after setting the environment variable!
https://docs.aws.amazon.com/ja_jp/sdk-for-go/v1/developer-guide/configuring-sdk.html

**Comment by tkao-cursive** [comment]
dlakjflkajdsflkj

**Comment by ilyesAj** [comment]
Can you please cherry pick the commit on the stable version , 0.13.7 is impacted by this error
