### ISSUE TITLE
update secretsmanager-caching for aws-sdk-v2

### ISSUE THREAD

**Issue by tgilino** [aws/aws-secretsmanager-caching-go#9]
We have been using the secretsmanager cache for a while now, and find it very useful. Now that aws-sdk-v2 has been available for general use for a while now, we are looking at updating from v1 to v2, but we would like to use a cache that has been updated to aws-sdk-v2 as well. Any plans?

**Comment by jbct** [comment]
Thank you for the request. At this time, we don't have any plans to upgrade this library to use AWS SDK v2. AWS SDK v1 is fully supported and will work alongside projects using AWS SDK v2.
